[FIX] hr_employee_calendar_planning: Compatibility with hr_attendance_report_theoretical_time
This commit fixes two errors:
- When from_datetime is passed from another location with a timezone set, the context_timestamp function raises an error:

ValueError: Not naive datetime (tzinfo is already set)

Steps to reproduce locally:

Install the hr_employee_calendar_planning and hr_attendance_report_theoretical_time modules.
Enable Attendances from Backend Settings / Attendances / Configuration  / Settings.
Set a calendar for the Mitchell Admin employee.
Try to check in with the employee. A traceback is raised.

- When _get_work_days_data_batch is called without the calendar parameter, it finds and replaces the calendar with the best matching calendar from calendar_ids. However, if no calendar is passed, no calendar should be replaced. Currently, it takes the first calendar created automatically by the hr_employee_calendar_planning module and uses it to compute the data. This causes the tests in the hr_attendance_report_theoretical_time module to fail because no calendar is passed to the function.