[FIX] hr_public_holidays: Wrong variable usage
Without this patch, opening the holidays app fails with:

    TypeError: publicHolidays.map is not a function

    http://localhost/hr_public_holidays/static/src/js/holidays_highlighter.js:25

Now it should be OK. Promises were being used as Array or String wrongly.